### ISSUE TITLE
测试了一天，不能运行

### ISSUE THREAD

**Issue by xuewlcn** [Cocean001/ngrok_install#1]
安装顺利进行后最后，提示完成。
但是 服务端没有运行起来，也就说编译失败了，提示服务目录没有那个文件。

令人最为诡异的是 go 没安装成功！！！

**Comment by Cocean001** [comment]
这个问题我也遇到了，初步排查是：

1. go官方升级版本的问题。
2. ngrok官方升级的问题，有个包不再支持了。

之后会找一个方法解决掉他

**Comment by Cocean001** [comment]
Hi @xuewlcn ，不能编译的问题已解决了。最新的脚本可以编译服务端。

发现是因为包声明冲突导致的。目录 `/usr/local/ngrok/src/github.com/rivo/uniseg/` 下出现了两个包 `gen_breaktest.go` 和 `gen_properties.go` 文件，不属于当前目录。把他们放到其他目录下就解决问题了。

但因为ngrok官方已经不再维护了，所以就在脚本里加了对应的修复代码。

至于 go 无法安装的问题，猜测可能是网络原因。可以深入研究下。
